### ISSUE TITLE
DOI view does not work?

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/graph-ryder-dashboard#2]
The Degree of Interest view is supposed to show the "forum network" of topics, posts and authors, given a starting point (for example a topic). But I cannot get it to display anything. No error message though, and the progress bar works when using search.

**Comment by luca** [comment]
I noticed that it didn't work, and it looks like it was never completed. 
Shall we hide it in the meantime?

**Comment by albertocottica** [comment]
Absolutely. No one uses it anyway!

**Comment by luca** [comment]
it's been hidden @albertocottica
